
#
# This make file works locally on the embedded Angstrom Linux or x64.
#
PROGRAM_NAME=menlo_cnc_asm

DEBUG_OPTIONS=-g

hello :	$(PROGRAM_NAME).c $(PROGRAM_NAME).h main.c
	cc $(DEBUG_OPTIONS) -o $(PROGRAM_NAME) $(PROGRAM_NAME).c main.c

clean :
	rm $(PROGRAM_NAME)
